name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push' && contains(github.ref, 'dev')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew.bat build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-app
          path: build/libs/*.jar

  deploy:
    if: github.event_name == 'pull_request' && contains(github.ref,'main')
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: kotlin-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB41E0AF525442F5A653EBBF6EB8C8BC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3198422A23AC4C3CADD5CB7716D7FE85 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37851CDEA875473DACC308CFB0E12CB2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'to-do'
          slot-name: 'Production'
          package: 'ToDo-0.0.1-SNAPSHOT.jar'
